"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project-root .env (one level above backend/).
# Real environment variables always win over .env values.
load_dotenv(BASE_DIR.parent / ".env")


def env_bool(key: str, default: bool = False) -> bool:
    """Parse a boolean environment variable ('1/true/yes/on')."""
    return os.environ.get(key, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(key: str, default: str = "") -> list[str]:
    """Parse a comma-separated environment variable into a list."""
    return [item.strip() for item in os.environ.get(key, default).split(",") if item.strip()]


# Insecure default kept ONLY for local development convenience. It is rejected
# below when DEBUG is off so it can never silently reach production.
_INSECURE_SECRET_KEY = "django-insecure-##4z$@nvumsvy__$-8lh0e9@9e36)$r&mhk!ut(--do5q_=(m#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or _INSECURE_SECRET_KEY
if not DEBUG and SECRET_KEY == _INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set to a unique secret value when DEBUG is off. "
        "Generate one with: python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\""
    )

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Fernet key used to encrypt stored connection secrets at rest. In production it
# must be set explicitly; in DEBUG it is derived from SECRET_KEY for convenience.
# Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
CONFIG_ENCRYPTION_KEY = os.environ.get("CONFIG_ENCRYPTION_KEY", "")
if not DEBUG and not CONFIG_ENCRYPTION_KEY:
    raise ImproperlyConfigured(
        "CONFIG_ENCRYPTION_KEY must be set when DEBUG is off so stored secrets "
        "can be encrypted at rest. Generate one with: python -c \"from "
        "cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    )


# Application definition

# ── Multi-tenancy (django-tenants): schema-per-tenant ─────────────────────────
# SHARED_APPS live in the public schema (tenant metadata / control plane).
# TENANT_APPS are created once per tenant schema (the product itself).
SHARED_APPS = [
    'django_tenants',
    'apps.tenancy',
    'apps.billing',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
]

TENANT_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'rest_framework',
    'django_filters',
    'apps.accounts',
    'apps.workflow',
    'apps.realtime',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = 'tenancy.Organization'
TENANT_DOMAIN_MODEL = 'tenancy.Domain'

# Per-tenant users (each tenant schema has its own user table).
AUTH_USER_MODEL = 'accounts.User'

# Where @login_required sends unauthenticated users, and where login returns to.
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/api/v1/realtime/dashboard/'

# ── Billing (Stripe) ──────────────────────────────────────────────────────────
# Empty keys → billing endpoints degrade gracefully (no live calls). Seat
# enforcement and usage metering work regardless of Stripe configuration.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
# Stripe Price IDs per seat package (set in production).
STRIPE_PRICES = {
    'team_5':  os.environ.get('STRIPE_PRICE_TEAM_5', ''),
    'team_10': os.environ.get('STRIPE_PRICE_TEAM_10', ''),
    'team_25': os.environ.get('STRIPE_PRICE_TEAM_25', ''),
    'team_50': os.environ.get('STRIPE_PRICE_TEAM_50', ''),
}

MIDDLEWARE = [
    # Must be first: resolves the tenant schema from the request host.
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # django-tenants backend manages the per-request schema search path.
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME':     os.environ.get('DB_NAME',     'neomonks_core'),
        'USER':     os.environ.get('DB_USER',     'neomonks'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'neomonks_dev'),
        'HOST':     os.environ.get('DB_HOST',     'localhost'),
        'PORT':     os.environ.get('DB_PORT',     '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    }
}

# Route reads/writes to the correct schema for the active tenant.
DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Production security headers (opt-in via DJANGO_SECURE=True behind HTTPS) ────
# Enable once the platform is served over TLS so dev (plain HTTP) is unaffected.
SECURE = env_bool("DJANGO_SECURE", False)
if SECURE:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Honour the proxy's X-Forwarded-Proto so SSL redirect works behind a load balancer.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ── Autonomous workflow settings ──────────────────────────────────────────────

# Directory where agent-written code is stored (one sub-dir per product/branch)
WORKFLOW_WORKSPACE = BASE_DIR / 'workspace'

# GitHub integration (set these as env vars in production)
GITHUB_TOKEN      = os.environ.get('GITHUB_TOKEN', '')
GITHUB_REPO       = os.environ.get('GITHUB_REPO', '')       # e.g. "org/repo"
GITHUB_BASE_BRANCH = os.environ.get('GITHUB_BASE_BRANCH', 'main')

# Default LLM model for CrewAI agents
DEFAULT_AGENT_MODEL = os.environ.get('DEFAULT_AGENT_MODEL', 'ollama/qwen2.5-coder:7b')

# Path where Ollama models are stored (passed as OLLAMA_MODELS env var when starting Ollama)
OLLAMA_MODELS_PATH = os.environ.get('OLLAMA_MODELS_PATH', r'E:\neomonks_tech\models')
OLLAMA_HOST       = os.environ.get('OLLAMA_HOST', 'http://localhost:11434')
# Force CPU-only: GPU has insufficient VRAM to hold model layers (causes CUDA_Host OOM)
OLLAMA_NUM_GPU    = int(os.environ.get('OLLAMA_NUM_GPU', '0'))

# Hard cap on concurrent background workers — prevents thread exhaustion
AUTONOMOUS_MAX_WORKERS = int(os.environ.get('AUTONOMOUS_MAX_WORKERS', 4))

# Hard timeout for any single LLM call (seconds) — prevents hung threads
LLM_TIMEOUT_SECONDS = int(os.environ.get('LLM_TIMEOUT_SECONDS', 300))

# Loop timing
LOOP_POLL_INTERVAL   = int(os.environ.get('LOOP_POLL_INTERVAL', 10))    # seconds between loop ticks
LOOP_PR_SYNC_INTERVAL = int(os.environ.get('LOOP_PR_SYNC_INTERVAL', 3600))  # PR sync every hour


# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.accounts.authentication.ApiKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Read: Viewer+, write: Member+, delete: Admin+. Account/admin views
        # override this with stricter role requirements.
        'apps.accounts.permissions.WorkflowRolePermission',
    ],
}
