# Generated by Django 5.2.14 on 2026-06-21 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='trial', max_length=50)),
                ('seats_purchased', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled')], default='TRIALING', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenancy.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AGENT_RUN', 'Agent run'), ('LLM_TOKENS', 'LLM tokens')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reported_to_stripe', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='billing_usa_organiz_956d96_idx')],
            },
        ),
    ]
