"""
Product Scaffolder
==================
When a new Product is created:
  1. Create  products/{slug}/  from the templates/ scaffold (skip node_modules, venv).
  2. Substitute {{product_name}} / {{product_slug}} placeholders in text files.
  3. Run  npm install  in  products/{slug}/frontend/
  4. Create a Python venv + install requirements in  products/{slug}/backend/
  5. Run  django-admin startproject core .  in the backend.
  6. Init a git repo inside  products/{slug}/  so agents can commit branches.

After scaffolding, the executor writes agent-generated files directly into
  products/{slug}/frontend/src/   and   products/{slug}/backend/apps/
"""
from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from django.conf import settings

logger = logging.getLogger(__name__)

# Root of the whole neomonks_core project (one level above backend/)
PROJECT_ROOT = Path(settings.BASE_DIR).parent
TEMPLATES_DIR = PROJECT_ROOT / "templates"
PRODUCTS_DIR = PROJECT_ROOT / "products"

# Directories to skip when copying the scaffold
SKIP_DIRS = {"node_modules", "venv", ".git", "__pycache__", ".mypy_cache", "dist", "build"}

# File extensions treated as text (for placeholder substitution)
TEXT_EXTENSIONS = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".json", ".html", ".css",
    ".md", ".txt", ".yml", ".yaml", ".toml", ".env", ".example",
    ".cfg", ".ini", ".sh", ".bat",
}


class ProductScaffolder:
    """Scaffold a new product folder from the templates/ directory."""

    def scaffold(self, product_name: str, product_slug: str) -> Path:
        """
        Full scaffold pipeline. Returns the product root path.
        Raises if the product folder already exists.
        """
        product_dir = PRODUCTS_DIR / product_slug

        if product_dir.exists():
            logger.info("Scaffolder: %s already exists, skipping copy", product_dir)
        else:
            logger.info("Scaffolder: creating %s from templates", product_dir)
            self._copy_template(product_dir, product_name, product_slug)
            logger.info("Scaffolder: template copied")

        # Run initialisation steps
        self._init_frontend(product_dir)
        self._init_backend(product_dir)
        self._init_git(product_dir, product_name)

        logger.info("Scaffolder: %s ready at %s", product_name, product_dir)
        return product_dir

    # ── private ──────────────────────────────────────────────────────────

    def _copy_template(self, dest: Path, product_name: str, product_slug: str) -> None:
        """Copy templates/ → products/{slug}/, skipping heavy dirs, substituting placeholders."""
        dest.mkdir(parents=True, exist_ok=True)

        for src_path in TEMPLATES_DIR.rglob("*"):
            # Skip directories and anything inside excluded dirs
            if any(part in SKIP_DIRS for part in src_path.parts):
                continue
            if src_path.is_dir():
                continue

            rel = src_path.relative_to(TEMPLATES_DIR)
            dst_path = dest / rel
            dst_path.parent.mkdir(parents=True, exist_ok=True)

            if src_path.suffix.lower() in TEXT_EXTENSIONS:
                try:
                    content = src_path.read_text(encoding="utf-8")
                    content = content.replace("{{product_name}}", product_name)
                    content = content.replace("{{product_slug}}", product_slug)
                    dst_path.write_text(content, encoding="utf-8")
                except UnicodeDecodeError:
                    shutil.copy2(src_path, dst_path)
            else:
                shutil.copy2(src_path, dst_path)

        # Create a top-level .env from .env.example if not already there
        env_example = dest / ".env.example"
        env_file = dest / ".env"
        if env_example.exists() and not env_file.exists():
            shutil.copy2(env_example, env_file)

        # README
        readme = dest / "README.md"
        if not readme.exists():
            readme.write_text(f"# {product_name}\n\nGenerated by NeoMonks autonomous workflow.\n")

    @staticmethod
    def _init_frontend(product_dir: Path) -> None:
        frontend_dir = product_dir / "frontend"
        if not frontend_dir.exists():
            logger.info("Scaffolder: no frontend dir, skipping npm install")
            return
        if (frontend_dir / "node_modules").exists():
            logger.info("Scaffolder: node_modules already present, skipping npm install")
            return
        logger.info("Scaffolder: running npm install in %s", frontend_dir)
        _run(["npm", "install"], cwd=frontend_dir)

    @staticmethod
    def _init_backend(product_dir: Path) -> None:
        backend_dir = product_dir / "backend"
        if not backend_dir.exists():
            logger.info("Scaffolder: no backend dir, skipping venv setup")
            return

        venv_dir = backend_dir / "venv"
        pip = venv_dir / ("Scripts" if sys.platform == "win32" else "bin") / "pip"

        if not venv_dir.exists():
            logger.info("Scaffolder: creating venv in %s", backend_dir)
            _run([sys.executable, "-m", "venv", "venv"], cwd=backend_dir)
        else:
            logger.info("Scaffolder: venv already present")

        req_file = backend_dir / "requirements.txt"
        if req_file.exists():
            logger.info("Scaffolder: installing backend requirements")
            _run([str(pip), "install", "-r", "requirements.txt"], cwd=backend_dir)

    @staticmethod
    def _init_git(product_dir: Path, product_name: str) -> None:
        git_dir = product_dir / ".git"
        if git_dir.exists():
            logger.info("Scaffolder: git repo already exists")
            return
        logger.info("Scaffolder: initialising git repo in %s", product_dir)
        try:
            from git import Repo
            repo = Repo.init(product_dir)
            # Stage all scaffolded files
            repo.git.add(".")
            repo.index.commit(f"chore: scaffold {product_name} [neomonks]")
            logger.info("Scaffolder: initial git commit done")
        except Exception as exc:
            logger.warning("Scaffolder: git init failed — %s", exc)


def _run(cmd: list[str], cwd: Path) -> None:
    """Run a subprocess, logging output. Does not raise on failure."""
    try:
        result = subprocess.run(
            cmd, cwd=str(cwd),
            capture_output=True, text=True, timeout=300,
        )
        if result.returncode != 0:
            logger.warning("Scaffolder cmd %s failed (rc=%d): %s", cmd, result.returncode, result.stderr[:500])
        else:
            logger.info("Scaffolder cmd %s OK", cmd[0])
    except FileNotFoundError:
        logger.warning("Scaffolder: command not found: %s", cmd[0])
    except subprocess.TimeoutExpired:
        logger.warning("Scaffolder: command timed out: %s", cmd)
    except Exception as exc:
        logger.warning("Scaffolder: unexpected error running %s: %s", cmd, exc)
