# Generated by Django 5.2.14 on 2026-06-01 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('SOLUTION_ARCHITECT', 'Solution Architect'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('INFRA_ADMIN', 'Infrastructure Admin'), ('QA_ENGINEER', 'QA Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('MLOPS_ENGINEER', 'MLOps Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('BI_DEVELOPER', 'BI Developer')], max_length=50)),
                ('model_name', models.CharField(default='claude-opus-4-6', help_text='LLM model this agent uses', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('allowed_paths', models.JSONField(default=list, help_text='Glob patterns of files/dirs this agent can edit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('ARCHITECTURE', 'Architecture'), ('PR', 'Pull Request'), ('TASK', 'Task')], max_length=50)),
                ('object_id', models.IntegerField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('decided_by', models.CharField(blank=True, max_length=255, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('source_document', models.TextField(blank=True, help_text='Original document or description')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=50)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('created_by', models.CharField(default='system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='workflow.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_json', models.JSONField(default=dict, help_text='Structured design document: components, data models, APIs, dependencies')),
                ('rationale', models.TextField(help_text='Why this design was chosen')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested')], default='DRAFT', max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='workflow.requirement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner_role', models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('SOLUTION_ARCHITECT', 'Solution Architect'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('INFRA_ADMIN', 'Infrastructure Admin'), ('QA_ENGINEER', 'QA Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('MLOPS_ENGINEER', 'MLOps Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('BI_DEVELOPER', 'BI Developer')], help_text='Role responsible for this task', max_length=50)),
                ('assigned_agent', models.CharField(blank=True, help_text='Human display name of assigned agent (e.g., Priya Nair)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('MERGED', 'Merged')], default='BLOCKED', max_length=50)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pr_url', models.URLField(blank=True, null=True)),
                ('estimate', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], help_text='Story points or time estimate', max_length=20)),
                ('order_index', models.IntegerField(default=0, help_text='Task order within product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflow.architectureartifact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.product')),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workflow.requirement')),
            ],
            options={
                'ordering': ['order_index', '-created_at'],
                'unique_together': {('product', 'branch_name')},
            },
        ),
        migrations.CreateModel(
            name='PullRequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('MERGED', 'Merged'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('merge_state', models.CharField(choices=[('CLEAN', 'Can Merge'), ('BLOCKED', 'Blocked'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('review_state', models.CharField(blank=True, help_text='APPROVED, CHANGES_REQUESTED, PENDING, etc.', max_length=255)),
                ('review_comments', models.JSONField(default=list, help_text='List of review comments')),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_record', to='workflow.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUIREMENT_CREATED', 'Requirement Created'), ('REQUIREMENT_REVIEWED', 'Requirement Reviewed'), ('REQUIREMENT_APPROVED', 'Requirement Approved'), ('REQUIREMENT_REJECTED', 'Requirement Rejected'), ('ARCHITECTURE_SUBMITTED', 'Architecture Submitted'), ('ARCHITECTURE_APPROVED', 'Architecture Approved'), ('ARCHITECTURE_CHANGES_REQUESTED', 'Architecture Changes Requested'), ('TASK_CREATED', 'Task Created'), ('TASK_READY', 'Task Ready'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_IN_PROGRESS', 'Task In Progress'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_IN_REVIEW', 'Task In Review'), ('TASK_APPROVED', 'Task Approved'), ('TASK_CHANGES_REQUESTED', 'Task Changes Requested'), ('TASK_MERGED', 'Task Merged'), ('LOCK_ACQUIRED', 'Lock Acquired'), ('LOCK_RELEASED', 'Lock Released'), ('LOCK_EXPIRED', 'Lock Expired'), ('PR_CREATED', 'PR Created'), ('PR_OPENED', 'PR Opened'), ('PR_REVIEWED', 'PR Reviewed'), ('PR_APPROVED', 'PR Approved'), ('PR_CHANGES_REQUESTED', 'PR Changes Requested'), ('PR_MERGED', 'PR Merged'), ('PR_CLOSED', 'PR Closed'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVAL_GRANTED', 'Approval Granted'), ('APPROVAL_DENIED', 'Approval Denied')], max_length=100)),
                ('entity_type', models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('ARCHITECTURE', 'Architecture'), ('TASK', 'Task'), ('LOCK', 'Lock'), ('PR', 'Pull Request'), ('APPROVAL', 'Approval')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', '-created_at'], name='workflow_wo_entity__6574a6_idx'), models.Index(fields=['event_type', '-created_at'], name='workflow_wo_event_t_44b348_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative path in repository', max_length=500)),
                ('locked_by_agent', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=50)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Lock auto-expires after this time')),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='workflow.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='workflow.task')),
            ],
            options={
                'ordering': ['-locked_at'],
                'unique_together': {('product', 'file_path', 'status')},
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='workflow.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='workflow.task')),
            ],
            options={
                'unique_together': {('task', 'depends_on_task')},
            },
        ),
    ]
