# Generated by Django 5.2.14 on 2026-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short biography / persona for the agent'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Years of experience (persona detail)'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skill strings that shape this agent's system prompt"),
        ),
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='Acceptance criteria the deliverable must satisfy (one per line)'),
        ),
        migrations.AddField(
            model_name='task',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='Technologies/libraries this task should use'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('SOLUTION_ARCHITECT', 'Solution Architect'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('INFRA_ADMIN', 'Infrastructure Admin'), ('QA_ENGINEER', 'QA Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('MLOPS_ENGINEER', 'MLOps Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('BI_DEVELOPER', 'BI Developer'), ('FLUTTER_DEVELOPER', 'Flutter Developer'), ('ANDROID_DEVELOPER', 'Android Developer'), ('IOS_DEVELOPER', 'iOS Developer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner_role',
            field=models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('SOLUTION_ARCHITECT', 'Solution Architect'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('INFRA_ADMIN', 'Infrastructure Admin'), ('QA_ENGINEER', 'QA Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('MLOPS_ENGINEER', 'MLOps Engineer'), ('DATA_SCIENTIST', 'Data Scientist'), ('BI_DEVELOPER', 'BI Developer'), ('FLUTTER_DEVELOPER', 'Flutter Developer'), ('ANDROID_DEVELOPER', 'Android Developer'), ('IOS_DEVELOPER', 'iOS Developer')], help_text='Role responsible for this task', max_length=50),
        ),
    ]
