# Generated by Django 5.2.14 on 2026-06-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_agentprofile_bio_agentprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='github_repo',
            field=models.CharField(blank=True, default='', help_text="GitHub repository for this product, e.g. 'org/repo'", max_length=255),
        ),
    ]
