# Generated by Django 5.2.14 on 2026-06-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_product_github_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_engine', models.CharField(blank=True, default='django.db.backends.postgresql', max_length=255)),
                ('db_name', models.CharField(blank=True, default='', max_length=255)),
                ('db_user', models.CharField(blank=True, default='', max_length=255)),
                ('db_password', models.CharField(blank=True, default='', max_length=255)),
                ('db_host', models.CharField(blank=True, default='', max_length=255)),
                ('db_port', models.CharField(blank=True, default='', max_length=10)),
                ('llm_mode', models.CharField(choices=[('ONLINE', 'Online (hosted API)'), ('LOCAL', 'Local (Ollama)')], default='LOCAL', max_length=20)),
                ('llm_provider', models.CharField(blank=True, choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('GOOGLE', 'Google Gemini'), ('GROQ', 'Groq'), ('MISTRAL', 'Mistral'), ('OPENROUTER', 'OpenRouter')], default='OPENAI', max_length=20)),
                ('llm_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('llm_model', models.CharField(blank=True, default='', max_length=255)),
                ('ollama_host', models.CharField(blank=True, default='', max_length=255)),
                ('ollama_model', models.CharField(blank=True, default='', max_length=255)),
                ('ollama_models_path', models.CharField(blank=True, default='', max_length=500)),
                ('github_token', models.CharField(blank=True, default='', max_length=255)),
                ('github_repo', models.CharField(blank=True, default='', max_length=255)),
                ('github_base_branch', models.CharField(blank=True, default='main', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform configuration',
                'verbose_name_plural': 'Platform configuration',
            },
        ),
    ]
