# Generated by Django 5.2.14 on 2026-06-21 07:35

import apps.workflow.fields
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    """Re-save existing rows so plaintext secrets are encrypted at rest.

    After the AlterField operations above, the historical model's secret
    fields are EncryptedCharField: reading a legacy plaintext value returns it
    unchanged, and saving re-writes it as ciphertext via get_prep_value.
    """
    Config = apps.get_model('workflow', 'PlatformConfiguration')
    for row in Config.objects.all():
        row.save(update_fields=['db_password', 'llm_api_key', 'github_token'])


def noop_reverse(apps, schema_editor):
    """Decryption-on-read keeps values usable if reversed; nothing to undo."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_platformconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfiguration',
            name='db_password',
            field=apps.workflow.fields.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='platformconfiguration',
            name='github_token',
            field=apps.workflow.fields.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='platformconfiguration',
            name='llm_api_key',
            field=apps.workflow.fields.EncryptedCharField(blank=True, default='', max_length=1024),
        ),
        migrations.RunPython(encrypt_existing_secrets, noop_reverse),
    ]
