# Generated by Django 5.2.14 on 2026-06-22 04:46

import apps.workflow.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('AZURE_AD', 'Microsoft Entra ID (Azure AD)'), ('GENERIC_OIDC', 'Generic OIDC')], default='AZURE_AD', max_length=20)),
                ('discovery_url', models.CharField(blank=True, default='', max_length=500)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', apps.workflow.fields.EncryptedCharField(blank=True, default='', max_length=1024)),
                ('allowed_email_domains', models.CharField(blank=True, default='', help_text='Comma-separated; empty allows any domain.', max_length=500)),
                ('default_role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=20)),
                ('auto_provision', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SSO configuration',
                'verbose_name_plural': 'SSO configuration',
            },
        ),
    ]
